/* Actual client code in a DOM mock. These tests do not certify real browsers. */
import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import '../src/core.js';
import {clientFixture} from './dom-fixture.mjs';
const core=globalThis.DRCore;
const empty={version:1,saved:[],watched:[],hideWatched:false,showEndingTones:false};
function storage(seed=empty){const data={'dr.state.v1':JSON.stringify(seed)};return {data,getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=v,result:()=>JSON.parse(data['dr.state.v1'])};}
const catalog=[{slug:'my-mister',t:'My Mister',n:'my mister',a:'나의 아저씨',page:0,y:2018,img:null},{slug:'my-liberation-notes',t:'My Liberation Notes',n:'my liberation notes',a:'나의 해방일지',page:1,y:2022,img:null}];
const shelf='<div class="shelfbar"><button id="shelfshare">Share</button></div><div id="shelfmount"></div>';
const search='<div class="searchblock"><input id="q"><div id="sug"></div><button id="gobtn">Go</button></div>';
const fire=(el,type,values={})=>{const e={target:el,preventDefault(){this.prevented=true;},...values};for(const fn of el.listeners[type]||[])fn(e);return e;};
const flush=async()=>{await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));};

test('two stale tabs save different titles without losing the earlier save',()=>{const s=storage(),a=core.createState(s),b=core.createState(s);a.toggle('saved','my-mister');b.toggle('saved','my-liberation-notes');assert.deepEqual(s.result().saved,['my-mister','my-liberation-notes']);});
test('stale-tab save retains watched history and preferences from another tab',()=>{const s=storage(),a=core.createState(s),b=core.createState(s);const next=a.read();next.watched=['my-mister'];next.hideWatched=true;next.showEndingTones=true;a.write(next);b.toggle('saved','my-liberation-notes');assert.deepEqual(s.result(),{...empty,saved:['my-liberation-notes'],watched:['my-mister'],hideWatched:true,showEndingTones:true});});
test('stale-tab removal preserves another tab addition',()=>{const s=storage({...empty,saved:['a','b']}),a=core.createState(s),b=core.createState(s);a.toggle('saved','c');b.toggle('saved','a');assert.deepEqual(s.result().saved,['b','c']);});
test('unrelated stale-tab write cannot resurrect a title removed elsewhere',()=>{const s=storage({...empty,saved:['a','b']}),a=core.createState(s),b=core.createState(s);a.toggle('saved','a');b.toggle('watched','c');assert.deepEqual(s.result().saved,['b']);assert.deepEqual(s.result().watched,['c']);});
test('Undo inserts at original position and preserves an unseen other-tab save',()=>{const s=storage({...empty,saved:['a','b','c']}),a=core.createState(s);a.toggle('saved','b');const b=core.createState(s);b.toggle('saved','d');const next=a.read();next.saved.splice(1,0,'b');a.write(next);assert.deepEqual(s.result().saved,['a','b','c','d']);});
test('shared import delta retains unseen titles and removed titles stay removed',()=>{const s=storage({...empty,saved:['a']}),a=core.createState(s),b=core.createState(s);a.toggle('saved','a');a.toggle('saved','c');const next=b.read();next.saved.push('b');b.write(next);assert.deepEqual(s.result().saved,['c','b']);});
test('state cleared elsewhere is not resurrected by an unrelated stale-tab write',()=>{const s=storage({...empty,saved:['a'],watched:['b'],hideWatched:true}),a=core.createState(s);delete s.data['dr.state.v1'];a.toggle('saved','c');assert.deepEqual(s.result(),{...empty,saved:['c']});});
test('merging failure keeps current-page changes and reports session-only persistence',()=>{const s=storage(),a=core.createState(s);s.getItem=()=>{throw Error('denied');};assert.doesNotThrow(()=>a.toggle('saved','a'));assert.equal(a.sessionOnly(),true);assert.deepEqual(a.read().saved,['a']);});
test('denied initial storage is disclosed before the first write',()=>{const warnings=[],a=core.createState({getItem(){throw Error('denied');}},s=>warnings.push(s));assert.equal(a.sessionOnly(),true);assert.equal(warnings.length,1);});
test('legacy migration retains every legacy bookmark on the first write',()=>{const s=storage();delete s.data['dr.state.v1'];s.data['sd.shelf']='["a","b"]';const a=core.createState(s);a.toggle('watched','c');assert.deepEqual(s.result().saved,['a','b']);assert.equal(s.data['sd.shelf'],'["a","b"]');});

for(const [field,value] of [['a',{}],['a',7],['n',7],['n',[]],['img',{}],['page','false'],['y',{}],['hue',Infinity]])test('catalog rejects malformed optional '+field+' ('+JSON.stringify(value)+')',()=>{assert.throws(()=>core.validIndex([{...catalog[0],[field]:value}]),/Invalid catalog/);});
test('catalog rejects duplicates, empty catalog and empty title but accepts optional omissions',()=>{for(const data of [[],[catalog[0],catalog[0]],[{slug:'a',t:' '}],[null]])assert.throws(()=>core.validIndex(data),/Invalid catalog/);assert.equal(core.validIndex([{slug:'a',t:'A'}]).length,1);assert.equal(core.validIndex(catalog),catalog);assert.equal(core.search(catalog,'나의 아저씨')[0].slug,'my-mister');});
test('malformed search response gives Retry and recovers after a valid response',async()=>{let attempts=0;const f=await clientFixture({html:search,fetcher:async()=>({ok:true,json:async()=>++attempts===1?[{...catalog[0],a:{}}]:catalog})});f.$('#q').value='my';fire(f.$('#q'),'input');assert.match(f.$('#searchstatus').textContent,/Could not load titles/);f.$('#searchretry').click();await flush();assert.match(f.$('#sug').textContent,/My Mister/);assert.equal(f.$('#q').getAttribute('aria-expanded'),'true');});
test('malformed shelf response retains stored IDs and Retry recovers',async()=>{let attempts=0;const f=await clientFixture({html:shelf,saved:['my-mister'],fetcher:async()=>({ok:true,json:async()=>++attempts===1?[{...catalog[0],img:{}}]:catalog})});assert.match(f.$('#shelfmount').textContent,/Your saved titles are unchanged/);assert.deepEqual(f.state().saved,['my-mister']);f.$('#shelfretry').click();await flush();assert.equal(f.$('.shelfitem').dataset.item,'my-mister');});

test('changing share fragment redraws titles without replacing the personal shelf',async()=>{const f=await clientFixture({html:shelf,index:catalog,saved:['my-mister'],hash:'#s=my-mister'});f.hashChange('#s=my-liberation-notes');assert.equal(f.$('.shelfitem').dataset.item,'my-liberation-notes');assert.deepEqual(f.state().saved,['my-mister']);f.$('#keepshelf').click();assert.deepEqual(f.state().saved,['my-mister','my-liberation-notes']);});
test('hash navigation handles damaged, valid, empty and personal shelves in sequence',async()=>{const f=await clientFixture({html:shelf,index:catalog,saved:['my-mister'],hash:'#s=my-mister'});f.hashChange('#s=%E0%A4%A');assert.match(f.$('#shelfmount').textContent,/Cannot open this shared shelf/);f.hashChange('#s=my-liberation-notes');assert.equal(f.$('.shelfitem').dataset.item,'my-liberation-notes');f.hashChange('#s=');assert.match(f.$('#shelfmount').textContent,/No recognized shared titles/);f.hashChange('');assert.equal(f.$('.shelfitem').dataset.item,'my-mister');assert.equal(f.$('#keepshelf'),null);});
test('hash changes clear old copy text, restore useful focus and copy the new shelf',async()=>{const f=await clientFixture({html:shelf,index:catalog,hash:'#s=my-mister'});f.$('#shelfshare').click();assert.match(f.$('#sharelink').value,/my-mister/);f.hashChange('#s=my-liberation-notes');assert.equal(f.$('#sharelink').value,'');assert.equal(f.$('#sharelink').parentNode.hidden,true);assert.equal(f.document.activeElement,f.$('#shelfshare'));f.$('#shelfshare').click();assert.match(f.$('#sharelink').value,/my-liberation-notes/);assert.equal(f.$('#sharelink').parentNode.hidden,false);});
test('hash change while catalog is loading renders the latest fragment',async()=>{let resolve;const f=await clientFixture({html:shelf,hash:'#s=my-mister',fetcher:()=>new Promise(r=>resolve=r)});f.hashChange('#s=my-liberation-notes');resolve({ok:true,json:async()=>catalog});await flush();assert.equal(f.$('.shelfitem').dataset.item,'my-liberation-notes');});
test('hash navigation retains connected focus after removing the focused shared title',async()=>{const f=await clientFixture({html:shelf,index:catalog,hash:'#s=my-mister'});f.$('.shelfitem button').focus();f.hashChange('#s=my-liberation-notes');assert.ok(f.document.body.contains(f.document.activeElement));assert.equal(f.document.activeElement.dataset.slug,'my-liberation-notes');});

for(const key of ['Enter','ArrowDown','ArrowUp','Escape'])test('composing '+key+' is left to the input method',async()=>{const f=await clientFixture({html:search,index:catalog}),q=f.$('#q');q.value='my';fire(q,'input');const e=fire(q,'keydown',{key,isComposing:true});assert.equal(e.prevented,undefined);assert.equal(f.context.location.href,undefined);});
test('legacy keyCode 229 cannot submit suggestions',async()=>{const f=await clientFixture({html:search,index:catalog}),q=f.$('#q');q.value='my';fire(q,'input');assert.equal(fire(q,'keydown',{key:'Enter',keyCode:229}).prevented,undefined);assert.equal(f.context.location.href,undefined);});
test('composition lifecycle closes stale suggestions and commits the completed Korean query',async()=>{const f=await clientFixture({html:search,index:catalog}),q=f.$('#q');q.focus();q.value='my';fire(q,'input');fire(q,'compositionstart');assert.equal(q.getAttribute('aria-expanded'),'false');q.value='나의 아저씨';fire(q,'input',{isComposing:true});fire(q,'keydown',{key:'Enter'});assert.equal(f.context.location.href,undefined);fire(q,'compositionend');assert.match(f.$('#sug').textContent,/My Mister/);fire(q,'keydown',{key:'Enter'});assert.equal(f.context.location.href,'/dramas/my-mister/');});
test('composition completion after blur does not reopen the list',async()=>{const f=await clientFixture({html:search,index:catalog}),q=f.$('#q');q.focus();fire(q,'compositionstart');q.value='my';f.document.body.focus();fire(q,'compositionend');assert.equal(q.getAttribute('aria-expanded'),'false');});
test('delayed catalog response cannot reopen suggestions during composition',async()=>{let resolve;const f=await clientFixture({html:search,fetcher:()=>new Promise(r=>resolve=r)}),q=f.$('#q');q.focus();q.value='my';fire(q,'input');fire(q,'compositionstart');resolve({ok:true,json:async()=>catalog});await flush();assert.equal(q.getAttribute('aria-expanded'),'false');fire(q,'compositionend');assert.equal(q.getAttribute('aria-expanded'),'true');});

test('actual short-collection predicate matches the client predicate at every boundary',()=>{const source=readFileSync('build.mjs','utf8'),block=source.slice(source.indexOf("slug: 'short-k-dramas'"));const expression=block.match(/where: ([^\n]+),/)[1];const predicate=vm.runInNewContext('('+expression+')',{DRCore:core});for(const episodes of [undefined,null,'',' ',0,-1,8.5,'8.5',{},[],true,Infinity,NaN,1,8,12,13,'12',' 8 '])assert.equal(predicate({episodes}),core.shortEpisodes(episodes),String(episodes));assert.match(source,/import '\.\/src\/core\.js';/);});


test('Retry restores keyboard focus to search before suggestions return',async()=>{let attempts=0;const f=await clientFixture({html:search,fetcher:async()=>({ok:++attempts>1,json:async()=>catalog})});f.$('#q').value='my';fire(f.$('#q'),'input');f.$('#searchretry').click();await flush();assert.equal(f.document.activeElement,f.$('#q'));fire(f.$('#q'),'keydown',{key:'ArrowDown'});assert.equal(f.$('#q').getAttribute('aria-activedescendant'),'suggestion-0');});
test('late clipboard failure for an old fragment does not announce a stale copy field',async()=>{let reject;const f=await clientFixture({html:shelf,index:catalog,hash:'#s=my-mister'});f.context.navigator.clipboard={writeText:()=>new Promise((resolve,r)=>reject=r)};f.$('#shelfshare').click();f.hashChange('#s=my-liberation-notes');reject(Error('denied'));await flush();assert.equal(f.$('#sharelink').value,'');assert.equal(f.$('.toast'),null);});
